application: rango-django-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: tango_with_django_project.wsgi.application

libraries:
- name: django
  version: 1.5
